# Generated by Django 4.0.6 on 2022-08-05 06:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.ImageField(blank=True, default='static/images/default.png', max_length=125, null=True, upload_to="media/user/"),
        ),
    ]
