# Generated by Django 4.0.6 on 2022-08-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='user_img',
        ),
    ]
