# Generated by Django 4.0.6 on 2022-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_customuser_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(blank=True, default='static/images/default.png', max_length=125, null=True, upload_to='images/user/'),
        ),
    ]
