# Generated by Django 4.0.6 on 2022-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_img',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, max_length=125, null=True, upload_to='media/user_img/'),
        ),
    ]
