# Generated by Django 4.0.6 on 2022-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_user_img_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, max_length=125, null=True, upload_to='user_img/', verbose_name='Your image'),
        ),
    ]
