# Generated by Django 4.0.6 on 2022-08-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
