# Generated by Django 4.0.6 on 2023-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='I have nothing to say...', max_length=255),
        ),
    ]
