# Generated by Django 4.0.6 on 2022-08-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, max_length=125, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
