# Generated by Django 4.0.6 on 2022-08-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(max_length=125, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.category'),
        ),
    ]
